### ISSUE TITLE
Individuelle Reihenfolge der Wichtige Länder wird ignoriert bzw. wieder alphabetisch geordnet

### ISSUE THREAD

**Issue by chuckki** [terminal42/contao-countryselect#12]
Laut der Beschreibung für "Wichtige Länder" : "Die hier ausgewählten Länder werden in der Reihenfolge in der sie hier eingegeben wurden in der Auswahl zuoberst aufgeführt." dachte ich, dass ich z.B. erst "Schweiz, Deutschland" eingeben kann. Jedoch wird nach dem Abspeichern die Reihenfolge automatisch in "Deutschland, Schweiz" geändert. Bug or Feature?

**Comment by fritzmg** [comment]
Die Reihenfolge ist aktuell immer alphabetisch.

**Comment by fritzmg** [comment]
Closen musst du ja nicht unbedingt - es muss ja offensichtlich entweder die Funktion oder die Beschreibung angepasst werden 😁
