### ISSUE TITLE
Data too long for column 'countryselect_exclude'

### ISSUE THREAD

**Issue by Funbug** [terminal42/contao-countryselect#13]
If I exclude all countries outside the EU, I get the following error message: 

`An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'countryselect_exclude' at row 1`

**Comment by fritzmg** [comment]
You could fix that error temporarily in your Contao instance via

```php
// contao/dca/tl_form_field.php
$GLOBALS['TL_DCA']['tl_form_field']['fields']['countryselect_exclude']['sql'] = ['type' => 'text', 'notnull' => false];
```

**Comment by Funbug** [comment]
Thanks, I did that. Just wanted to submit the issue. :)

**Comment by aschempp** [comment]
I don't see a reason these would ever have been varchars, changed in 0e86579dc0fafd2d7d90a191f36fa037b899f13c
