### ISSUE TITLE
CH instead ch

### ISSUE THREAD

**Issue by netzarbeiter** [terminal42/contao-countryselect#17]
Contao 4.13

I have a formualr and the data is stored in `tl_member`. The extension uses capital letters for the country code, but in Contao lower case letters are used.

![Bildschirmfoto 2024-03-13 um 14 30 44](https://github.com/terminal42/contao-countryselect/assets/1942550/812cbf0c-501d-4201-91d6-b8314847efdb)
![Bildschirmfoto 2024-03-13 um 14 26 28](https://github.com/terminal42/contao-countryselect/assets/1942550/84dace30-4758-4225-9d9d-997f4f6a521e)

**Comment by aschempp** [comment]
yes. Contao 4.13 uses lowercase, which is incorrect. It was changed to uppercase in Contao 5. Since the form generator does not allow to transform the value, I don't see a way to store "random" data to an existing system table.
