### ISSUE TITLE
Default values and support for insert tags

### ISSUE THREAD

**Issue by simonreitinger** [terminal42/contao-countryselect#6]
It seems like there is no support for a default value.
For the meantime, I extended the `addAttributes` method as a custom local extension but I think it would make sense to implement it here:

<pre>
public function addAttributes($arrAttributes)
    {
        parent::addAttributes($arrAttributes);
        $arrOptions = array(array('label' => ($this->placeholder == '' ? '-' : $this->placeholder), 'value' => ''));
        $arrCountries = $this->getCountries();

        if (strpos($this->varValue, '{{') !== false) {
            $this->varValue = \Contao\Controller::replaceInsertTags($this->value);
        }

        foreach ($arrCountries as $short => $name) {
            $option = array('label' => $name, 'value' => $short);

            if($this->varValue === $short) {
                $option['default'] = true;
            }

            $arrOptions[] = $option;
        }

        $this->arrOptions = $arrOptions;
    }

**Comment by fritzmg** [comment]
Default values are perfectly possible. What exactly did you choose for your default value? It needs to be a country code of course.

**Comment by simonreitinger** [comment]
Thank you for answering 👍 

I chose `{{user::country}}` as default value, so the issue is more about supporting insert tags.

The insert tag has to be replaced before rendering the select menu, so it gets handled just as a standard default text value like `de`.

With the code above it works perfectly fine - so I don't understand why that isn't possible in general 🤔 

Do you mean its more of a Contao issue than of this extension?

**Comment by fritzmg** [comment]
> With the code above it works perfectly fine - so I don't understand why that isn't possible in general 🤔
> 
> Do you mean its more of a Contao issue than of this extension?

I meant it would not be possible for regular select menus in Contao either :). If you want general support for this, you should create an appropriate Pull Request for Contao.

**Comment by aschempp** [comment]
I'm not sure a pull request for Contao makes sense, as the value in the frontend *would* be replaced anyway. It just does not work for the countryselect as it's value is used internally and not in the frontend. A pull request would be very welcome though 😊

**Comment by simonreitinger** [comment]
I have it on my to do list 😄 
If I have time in the next few weeks I'll create a PR for Contao, so this issue can be closed.

**Comment by aschempp** [comment]
Imho please create a PR for this extension, it's not a core issue…

**Comment by Toflar** [comment]
Closing in favor of the PR.
